CREATE SCHEMA IF NOT EXISTS bronze_layer;  
CREATE SCHEMA IF NOT EXISTS silver_layer;                #to create the silver layer schema.



DROP TABLE IF EXISTS medical_staging;

CREATE TABLE medical_staging (
    Change_Type TEXT,
    Covered_Recipient_Type TEXT,
    Teaching_Hospital_CCN TEXT,
    Teaching_Hospital_ID TEXT,
    Teaching_Hospital_Name TEXT,
    Covered_Recipient_Profile_ID TEXT,
    Covered_Recipient_NPI TEXT,
    Covered_Recipient_First_Name TEXT,
    Covered_Recipient_Middle_Name TEXT,
    Covered_Recipient_Last_Name TEXT,
    Covered_Recipient_Name_Suffix TEXT,
    Recipient_Primary_Business_Street_Address_Line1 TEXT,
    Recipient_Primary_Business_Street_Address_Line2 TEXT,
    Recipient_City TEXT,
    Recipient_State TEXT,
    Recipient_Zip_Code TEXT,
    Recipient_Country TEXT,
    Recipient_Province TEXT,
    Recipient_Postal_Code TEXT,
    Covered_Recipient_Primary_Type_1 TEXT,
    Covered_Recipient_Primary_Type_2 TEXT,
    Covered_Recipient_Primary_Type_3 TEXT,
    Covered_Recipient_Primary_Type_4 TEXT,
    Covered_Recipient_Primary_Type_5 TEXT,
    Covered_Recipient_Primary_Type_6 TEXT,
    Covered_Recipient_Specialty_1 TEXT,
    Covered_Recipient_Specialty_2 TEXT,
    Covered_Recipient_Specialty_3 TEXT,
    Covered_Recipient_Specialty_4 TEXT,
    Covered_Recipient_Specialty_5 TEXT,
    Covered_Recipient_Specialty_6 TEXT,
    Covered_Recipient_License_State_code1 TEXT,
    Covered_Recipient_License_State_code2 TEXT,
    Covered_Recipient_License_State_code3 TEXT,
    Covered_Recipient_License_State_code4 TEXT,
    Covered_Recipient_License_State_code5 TEXT,
    Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name TEXT,
    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID TEXT,
    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name TEXT,
    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State TEXT,
    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country TEXT,
    Total_Amount_of_Payment_USDollars TEXT,
    Date_of_Payment TEXT,
    Number_of_Payments_Included_in_Total_Amount TEXT,
    Form_of_Payment_or_Transfer_of_Value TEXT,
    Nature_of_Payment_or_Transfer_of_Value TEXT,
    City_of_Travel TEXT,
    State_of_Travel TEXT,
    Country_of_Travel TEXT,
    Physician_Ownership_Indicator TEXT,
    Third_Party_Payment_Recipient_Indicator TEXT,
    Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value TEXT,
    Charity_Indicator TEXT,
    Third_Party_Equals_Covered_Recipient_Indicator TEXT,
    Contextual_Information TEXT,
    Delay_in_Publication_Indicator TEXT,
    Record_ID TEXT,
    Dispute_Status_for_Publication TEXT,
    Related_Product_Indicator TEXT,
    Covered_or_Noncovered_Indicator_1 TEXT,
    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1 TEXT,
    Product_Category_or_Therapeutic_Area_1 TEXT,
    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1 TEXT,
    Associated_Drug_or_Biological_NDC_1 TEXT,
    Associated_Device_or_Medical_Supply_PDI_1 TEXT,
    Covered_or_Noncovered_Indicator_2 TEXT,
    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2 TEXT,
    Product_Category_or_Therapeutic_Area_2 TEXT,
    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2 TEXT,
    Associated_Drug_or_Biological_NDC_2 TEXT,
    Associated_Device_or_Medical_Supply_PDI_2 TEXT,
    Covered_or_Noncovered_Indicator_3 TEXT,
    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3 TEXT,
    Product_Category_or_Therapeutic_Area_3 TEXT,
    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3 TEXT,
    Associated_Drug_or_Biological_NDC_3 TEXT,
    Associated_Device_or_Medical_Supply_PDI_3 TEXT,
    Covered_or_Noncovered_Indicator_4 TEXT,
    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4 TEXT,
    Product_Category_or_Therapeutic_Area_4 TEXT,
    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4 TEXT,
    Associated_Drug_or_Biological_NDC_4 TEXT,
    Associated_Device_or_Medical_Supply_PDI_4 TEXT,
    Covered_or_Noncovered_Indicator_5 TEXT,
    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5 TEXT,
    Product_Category_or_Therapeutic_Area_5 TEXT,
    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5 TEXT,
    Associated_Drug_or_Biological_NDC_5 TEXT,
    Associated_Device_or_Medical_Supply_PDI_5 TEXT,
    Program_Year TEXT,
    Payment_Publication_Date TEXT
);





COPY bronze_layer.medical_staging
FROM '/tmp/OP_DTL_GNRL_PGYR2024_P01232026_01102026.csv'
WITH (
    FORMAT csv,
    HEADER true,
    DELIMITER ',',
    QUOTE '"',
    ESCAPE '"'
);